### ISSUE TITLE
WinAscent is wrong again

### ISSUE THREAD

**Issue by RosaWagner** [bettergui/BeVietnamPro#8]
The font finally got into sandbox. 

In the sources I sent you last time, WinAscent was 1261, and somehow, in the file you sent me to ship to google it is now 1000. So, as discussed, multiple times, it creates clipping in browser: the top of some vietnamese accents are cut. Since use_typo_metrics is now enabled, we don't need typoAscender to equal WinAscent.

I can't send it to production. 

![Capture d’écran 2021-08-12 à 12 18 46](https://user-images.githubusercontent.com/12222436/129180703-2a535071-1334-438b-aade-da10e21ca969.png)

**Comment by bettergui** [comment]
Hi Rosa, we are still confused about what happened but we think we got a fix as follows:
1. We doublechecked what we sent you and verified that all WinAscent had been 1261:
<img width="1040" alt="Screen Shot 2021-08-14 at 2 13 30 AM" src="https://user-images.githubusercontent.com/34254100/129441165-b9c6a8b6-5c8e-46c8-a65b-401331334eb7.png">

2. The values which were 1000 were actually sTypoAscender:
<img width="332" alt="Screen Shot 2021-08-14 at 2 08 39 AM" src="https://user-images.githubusercontent.com/34254100/129441173-c139c610-22b5-46f1-b7f0-0e17bab0de72.png">

3. We changed sTypoAscender to 1261, converted the ttx back to ttf, checked with Glyphs, and saw no clippings.
check bằng glyph thì đã báo ascender thành 1261 -> hết bị clipping
<img width="741" alt="Screen Shot 2021-08-14 at 2 07 02 AM" src="https://user-images.githubusercontent.com/34254100/129441129-1aaa9117-381d-4b6d-a926-3b4693f7a87e.png">

We just pushed the changes above: https://github.com/bettergui/BeVietnamPro/commit/10058fd8be4e32b43e5ac17e80faef4c2b67b9da
Would you mind helping us check if this works?

**Comment by RosaWagner** [comment]
You are not supposed to do that with ttx. It means that every time you modify the sources (.glyphs), then you have to do the little trick with ttx, which is not a practical, nor handy for users forking your repo, and result in this kind of confusion. We need a scalable production workflow; which mean no inconsistencies between your sources and your exported fonts. I set it up for you already.

In the masters' information in the source files, this is where the problem is, and this is were it needs to be fixed:

<img width="311" alt="Capture d’écran 2021-08-14 à 12 39 41" src="https://user-images.githubusercontent.com/12222436/129443694-4109f5c6-f4b3-49a1-8834-655a613d7173.png">

When done, then you reexport the fonts (or I do it  if needed) with `gftools builder` as explained in the README.md, and then I ship it.

If the using `gftools` is somehow too complicated, then I set up a workflow that does it for you automatically whenever you modify the sources.

**Comment by bettergui** [comment]
We want to do this right, and we appreciate you are helping us do so.

The sources have been fixed, and we have just exported the ttf files using the `gftools`.
We haven't found a good way to test whether this will still be clipped. Can you teach us how to test the result, @RosaWagner ? 

<img width="528" alt="Screen Shot 2021-08-14 at 10 54 50 PM" src="https://user-images.githubusercontent.com/34254100/129469434-ddd34c99-b041-4e6f-83fd-2aaea8d1c41b.png">
Newest changes have been pushed: 
 https://github.com/bettergui/BeVietnamPro/commit/804e62d81abbbcdcce5686069c69b41b8c245192

**Comment by yellow-type-foundry** [comment]
@RosaWagner Hi Rosa, do you need any further assistance from us? Hope to solve this soon, thank you!

**Comment by RosaWagner** [comment]
Hi
Sorry i was off for a week. You can just test the font in any browser and see if the glyph that has the tallest bouding-box is clipping. Like using these testing pages: https://idiotproofed.com, https://wakamaifondue.com etc.

Or in Glyphs you have a plugin "show vertical metrics", you can see if the win-metrics are going too low or not.

**Comment by RosaWagner** [comment]
Our QA tool have a problem since last week, I'll ship the font when it is fixed

**Comment by yellow-type-foundry** [comment]
That sounds good @RosaWagner Let us know if you need our help!

**Comment by yellow-type-foundry** [comment]
@RosaWagner Hi Rosa, have you got any update on this?

**Comment by RosaWagner** [comment]
Yep I shipped and merged it. We can close this issue :)
